### ISSUE TITLE
Install CyLP on Windows 10 with Cbc

### ISSUE THREAD

**Issue by snio89** [coin-or/CyLP#123]
<b>[Question]</b>
Does the CyLP for Windows come with the latest Cbc?

<b>[Details]</b>
I have tried to install CyLP on Windows 10. Here is the process I tried:

1. Prepare a clean Windows 10 environment.
2. Install anaconda.
3. Install Visual Studio Redistributable 2008, 2010, 2012, 2013, and 2015-2019.
4. Install Visual Studio Build Tools 2019.
5. `conda create -n env_cbc python=3.9 numpy scipy`
6. `activate env_cbc`
7. `pip install cylp`

Visual Studio things are installed for two purposes. First, I have a plan to use CVXPY. CVXPY requires Visual Studio Build Tools [#](https://www.cvxpy.org/install/index.html). Secondly, Cbc binaries are comes with different msvc versions [#](https://www.coin-or.org/download/binary/Cbc/).

<b>[Expected]</b>
README of CyLP identifies following two sentences.
1. "You will also need to install binaries for Cbc. The version should be 2.10 (recommended) or earlier (current master branch of Cbc will not work with this version of CyLP)."
2. "On Windows, a binary wheel is available and it is not necessary to install Cbc."

The second sentence makes me uncertain: does it means "if you don't need Cbc, you can pass its installation" or "by installing CyLP, Cbc will come with its binary wheel?"

Therefore, I tested a simple MILP. I expected either an error because of no Cbc installation or normal operation with Cbc 2.10. The program code follows:
```
import cylp
from cylp.cy import CyClpSimplex

def lp_case():
    print("\nLP Case")
    
    model = CyClpSimplex()
    x = model.addVariable('x', 1)
    y = model.addVariable('y', 1)
    model += x >= 0
    model += y >= 0
    model += x + y <= 1.5

    model.objective = x + 2 * y
    model.optimizationDirection = 'max'

    model.primal()

    x_opt = model.primalVariableSolution['x'][0]
    y_opt = model.primalVariableSolution['y'][0]
    print(x_opt, y_opt) # 0.0, 1.5
    

def milp_case():
    print("\nMILP Case")
    
    model = CyClpSimplex()
    x = model.addVariable('x', 1, isInt = True)
    y = model.addVariable('y', 1, isInt = True)
    model += x >= 0
    model += y >= 0
    model += x + y <= 1.5

    model.objective = x + 2 * y
    model.optimizationDirection = 'max'
    
    cbcModel = model.getCbcModel()  # Clp -> Cbc model / LP -> MIP
    status = cbcModel.solve()
    print("\nStatus")
    print(status)

    x_opt = cbcModel.primalVariableSolution['x'][0]
    y_opt = cbcModel.primalVariableSolution['y'][0]
    print("\nResult")
    print(x_opt, y_opt) # 0.0, 1.0


if __name__ == '__main__':
    
    print("CyLP version: " + cylp.__version__) # 0.91.0
    lp_case()
    milp_case()
```

<b>[Result]</b>
```
MILP Case
Welcome to the CBC MILP Solver
Version: 2.10.5
Build Date: Feb  9 2021
...
```

<b>[Problem]</b>

The installation of CyLP on Windows 10 comes with the latest Cbc. However, the Cbc version 2.10 is recommended for CyLP because of the API issue [#](https://github.com/coin-or/CyLP/issues/91). Is it okay to use CyLP on Windows with the latest Cbc? Or is it necessary to find a method to downgrade the Cbc version?

I know Cbc and CyLP are mainly supported for the Linux environment. If this is an issue that is hard to be solved, I would try a docker environment without any problem. Thanks.

**Comment by tkralphs** [comment]
The binary wheel that you get when you install the most recent release of CyLP in Windows 10 with `pip` is version 2.10.5, as shown in your output above. This is the correct recommended version. The version that will _not_ work is the current `master` branch and this is what is discussed in #91 . CyLP will not even build with the `master` version of Cbc so there would be no way for you to install CyLP at all with that version. You should have no problem with any version that pip installs from Pypi in Windows.

Just FYI, it is not the case that Cbc and CyLP are mainly supported for Linux. We regularly build and test on all major platforms and binary wheels for Windows are built with every release. Windows is in fact the only platform for which we build binary wheels, since it is straightforward to do so. Binary wheels for Linux are a bit more involved. For Linux I would instead recommend installing the conda package `coin-or-clp`.

**Comment by snio89** [comment]
I appreciate your comment and support for all these libraries. Thank you for your help.
