### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by cafunechen** [coin-or/CyLP#137]
Hi,  i install cylp according to:
1、 conda create -n cbc python=3.7 coin-or-cbc -c conda-forge
2、conda activate cbc
3、pip install cylp

it's ok to execute “import cylp"
but when i execute the demo

```
import numpy as np
from cylp.cy import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray

s = CyClpSimplex()

# Add variables
x = s.addVariable('x', 3)
y = s.addVariable('y', 2)

# Create coefficients and bounds
A = np.matrix([[1., 2., 0],[1., 0, 1.]])
B = np.matrix([[1., 0, 0], [0, 0, 1.]])
D = np.matrix([[1., 2.],[0, 1]])
a = CyLPArray([5, 2.5])
b = CyLPArray([4.2, 3])
x_u= CyLPArray([2., 3.5])

# Add constraints
s += A * x <= a
s += 2 <= B * x + D * y <= b
s += y >= 0
s += 1.1 <= x[1:3] <= x_u

# Set the objective function
c = CyLPArray([1., -2., 3.])
s.objective = c * x + 2 * y.sum()

# Solve using primal Simplex
s.primal()
print s.primalVariableSolution['x']

```

the error occurs：  

```
7f400058c000-7f400258c000 rw-p 00000000 00:00 0
7f4002594000-7f4002598000 r--p 00000000 103:04 5817767                   ~/miniconda3/envs/cbc/lib/python3.7/site-packages/cylp/cy/CyCglCutGeneratorBase.cpython-37m-x86_64-linux-gnu.so
7f4002598000-7f400259d000 r-xp 00004000 103:04 5817767                   ~/miniconda3/envs/cbc/lib/python3.7/site-packages/cylp/cy/CyCglCutGeneratorBase.cpython-37m-x86_64-linux-gnu.so
7f400259d000-7f400259f000 r--p 00009000 103:04 5817767                   ~/miniconda3/envs/cbc/lib/python3.7/site-packages/cylp/cy/CyCglCutGeneratorBase.cpython-37m-x86_64-linux-gnu.so
7f400259f000
...
7f401f662000-7f401f669000 r--s 00000000 103:04 4196451                   /usr/lib64/gconv/gconv-modules.cache
...
7f401f669000-7f401f66a000 rw-p 00000000 00:00 0
7f401f66a000-7f401f66b000 r--p 00021000 103:04 4067138                   /usr/lib64/ld-2.17.so
7f401f66b000-7f401f66c000 rw-p 00022000 103:04 4067138                   /usr/lib64/ld-2.17.so
7f401f66c000-7f401f66d000 rw-p 00000000 00:00 0
7f401f66d000-7f401f6c8000 r--p 00000000 103:04 5812395                  ~/miniconda3/envs/cbc/bin/python3.7
7f401f6c8000-7f401f8b6000 r-xp 0005b000 103:04 5812395                   ~/miniconda3/envs/cbc/bin/python3.7
7f401f8b6000-7f401f967000 r--p 00249000 103:04 5812395                   ~/miniconda3/envs/cbc/bin/python3.7
7f401f968000-7f401f96b000 r--p 002fa000 103:04 5812395                  ~/miniconda3/envs/cbc/bin/python3.7
7f401f96b000-7f401f9d4000 rw-p 002fd000 103:04 5812395                  ~/miniconda3/envs/cbc/bin/python3.7
7f401f9d4000-7f401f9f4000 rw-p 00000000 00:00 0
7f402100b000-7f402154b000 rw-p 00000000 00:00 0                          [heap]
7ffc0599e000-7ffc059bf000 rw-p 00000000 00:00 0                          [stack]
7ffc059f4000-7ffc059f6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

i don't know what mistake has happened ，Please help me！ thanks a lot

**Comment by tkralphs** [comment]
I just repeated the steps and it was successful for me, though I had to make some slight modifications to get it to work. Since you don't mention having to do this, I suspect something is corrupted up in your environment. The most obvious source of problems (which I also ran into) is that it is easy to accidentally execute the wrong version of `pip` when in a conda environment. To be safe, you should do
```
python -m pip install cylp
```
I guess that the pip you are using must be the wrong one, since if it was the right one you would have next run into the problem that `numpy` must be installed manually before installing cylp. I don't have a workaround for this at the moment, although I'm sure there must be one. So you should either install numpy when creating the environment by doing
```
conda create -n cbc python=3.7 coin-or-cbc numpy -c conda-forge
```
or if the environment is already created, then do
```
python-m pip install numpy
```
If there were no errors when you installed cylp in this clean environment, then you were probably using the wrong version of pip. I don't know exactly how you were then able to import cylp, but in any case, it works fine for me once I install numpy and also use the right version of pip.

**Comment by tkralphs** [comment]
Another indication that something weird is going on is that the script in the README (and the on you copied above was accidentally a Python 2 script, so if you didn't get any error when you ran it, then you ran it in Python 2 (unless you corrected this and didn't mention it). The README has now been modified to reflect all of the small glitches I ran into and that are discussed above.

**Comment by cafunechen** [comment]
Thanks for your patience， I've tried a lot of method, but it just doesn't work. I tried what you just mentioned, and it still didn't work.
But this time the error is different（maybe it's because I tried it on the MAC, problem 137 occur on Linux）:
` from cylp.cy import CyClpSimplex
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cylp/cy/__init__.py", line 1, in <module>
    from .CyCoinIndexedVector import CyCoinIndexedVector
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cylp/cy/CyCoinIndexedVector.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libCbcSolver.3.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cylp/cy/CyCoinIndexedVector.cpython-37m-darwin.so
  Reason: tried: '/usr/lib/libCbcSolver.3.dylib' (no such file)
`

**Comment by tkralphs** [comment]
@cafunechen I'm confused, since you said [here](https://github.com/coin-or/CyLP/issues/135#issuecomment-976165253) that it works on Linux. 

Bu anyway, for this current error, it looks like maybe you are mixing conda Python with the Python that comes with OS X or something. This kind of corruption is pretty common on OS X. The version of cylp getting loaded is from `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cylp/` as you see in the error and this is not where a conda package installed in a conda environment should be located. You probably need to research a little more about how conda and Apple's installed Python interact to be able to debug this yourself. It's difficult for me to really tell what's going on. 

It would probably work to just delete the directory `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cylp/` or uninstall cylp from within the OS X Python. But none of this is really a problem with CyLP.

**Comment by cafunechen** [comment]
my environment are:
1、python ->3.7.12
numpy -> 1.21.4
scipy->1.7.3
pip -> 21.3.1

2、gcc -> gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

thanks

**Comment by cafunechen** [comment]
> s = CyClpSimplex()

hi，i guess the error occurs for the version of **_glibc_** compilation is inconsistent with the system version，Is there a specific version about **_glibc_**

**Comment by tkralphs** [comment]
There is no specific version of libc. CyLP is built from source on OS X and Linux, so you get whatever libc version the compiler links to (OS X doesn't actually use glibc, but instead uses the LLVM libc I believe). 

This is just a stab in the dark, but could you take a look at #105 and try building this commit: 875d5d5? If this fixes it, then we would have a clue.

**Comment by cafunechen** [comment]
> There is no specific version of libc. CyLP is built from source on OS X and Linux, so you get whatever libc version the compiler links to (OS X doesn't actually use glibc, but instead uses the LLVM libc I believe).
> 
> This is just a stab in the dark, but could you take a look at #105 and try building this commit: [875d5d5](https://github.com/coin-or/CyLP/commit/875d5d5ad07cd1b4b53d3715e4aa29164a025e9f)? If this fixes it, then we would have a clue.
i bulid the cylp [875d5d5](https://github.com/coin-or/CyLP/commit/875d5d5ad07cd1b4b53d3715e4aa29164a025e9f), and the 
```
from cylp.cy import CyClpSimplex
```
occurs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/CyLP/cylp/cy/__init__.py", line 1, in <module>
    from .CyCoinIndexedVector import CyCoinIndexedVector
ModuleNotFoundError: No module named 'cylp.cy.CyCoinIndexedVector'
```
Whether this version  [875d5d5] is special  import way  in some dependency packages？ 
and 
```
import cylp 
```
it still normal, no errors reported. 
by the way ,the OS problem mentioned last time has been solved and can be used normally, thanks! but I want to use cylp on Linux, the reason I installed it on a MAC is just make sure my installation steps correctly.

**Comment by cafunechen** [comment]
> > There is no specific version of libc. CyLP is built from source on OS X and Linux, so you get whatever libc version the compiler links to (OS X doesn't actually use glibc, but instead uses the LLVM libc I believe).
> > This is just a stab in the dark, but could you take a look at #105 and try building this commit: [875d5d5](https://github.com/coin-or/CyLP/commit/875d5d5ad07cd1b4b53d3715e4aa29164a025e9f)? If this fixes it, then we would have a clue.
> 
> i bulid the cylp [875d5d5](https://github.com/coin-or/CyLP/commit/875d5d5ad07cd1b4b53d3715e4aa29164a025e9f), through `python setup.py install ` and the
> 
> ```
> from cylp.cy import CyClpSimplex
> ```
> 
> occurs
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "~/CyLP/cylp/cy/__init__.py", line 1, in <module>
>     from .CyCoinIndexedVector import CyCoinIndexedVector
> ModuleNotFoundError: No module named 'cylp.cy.CyCoinIndexedVector'
> ```
> 
> Whether this version [[875d5d5](https://github.com/coin-or/CyLP/commit/875d5d5ad07cd1b4b53d3715e4aa29164a025e9f)] is special import way in some dependency packages？ and
> 
> ```
> import cylp 
> ```
> 
> it still normal, no errors reported. by the way ,the OS problem mentioned last time has been solved and can be used normally, thanks! but I want to use cylp on Linux, the reason I installed it on a MAC is just make sure my installation steps correctly.
