### ISSUE TITLE
sdist should ship Cython sources

### ISSUE THREAD

**Issue by mkoeppe** [coin-or/CyLP#152]

**Comment by tkralphs** [comment]
It looks like `setup.py` is already set up to do this, but it only includes `.pyx` in `sdist` when run with `CYLP_USE_CYTHON` set and I probably just didn't do that when making the previous releases.

**Comment by mkoeppe** [comment]
Hence #149?

**Comment by tkralphs** [comment]
#149 is definitely useful, although I also usually upload a binary wheel for Windows when I do a release so I need a workflow for that in order to replace my manual release workflow with an Action (which would be great! But I don't see the connection of #149 to what I said above. I guess #149 would need to be modified to set `CYLP_USE_CYTHON` in order to ensure that the `.pyx` files are properly included.

**Comment by mkoeppe** [comment]
Or you can just list the file as `package_data`, or you can add them to `MANIFEST.in`.

**Comment by mkoeppe** [comment]
On my machine, without `CYLP_USE_CYTHON`, it already includes the `.pyx` files in the sdist. So I think it's a matter of whether you build the sdist with (recent enough) setuptools or plain distutils. 
Either way - #149 will take the variation out of it.

**Comment by mkoeppe** [comment]
> I also usually upload a binary wheel for Windows when I do a release so I need a workflow for that

This doesn't have to be done at the same time

**Comment by tkralphs** [comment]
> On my machine, without CYLP_USE_CYTHON, it already includes the .pyx files in the sdist. So I think it's a matter of whether you build the sdist with (recent enough) setuptools or plain distutils.

Hmm, OK, thanks for that data point. The Cython documentation seems to say something different and recommends basically the setup that we have. But I must be missing something. 

> This doesn't have to be done at the same time

Yes, I just meant that if I'm already uploading a wheel, uploading the sdist is almost no additional work. But if I could get an action to do both, that would really help.

**Comment by mkoeppe** [comment]
Would you accept a PR that makes `CYLP_USE_CYTHON` the only supported behavior, declares Cython as "build-system requires" in pyproject.toml, and removes the generated files from the repo?

**Comment by tkralphs** [comment]
I guess the argument against doing that is that with the current setup, I can build and test with with a fixed version of Cython that I know works and anyone who grabs the code will be using the files generated with that fixed version. It seems that what will inevitably happen otherwise is that the code will eventually fail to work with the latest Cython and there will be no way for a user to know what version of Cython would work. Are you suggesting pegging the Cython version? Would the idea be that you build CyLP in a virtual environment with a fixed Cython version? I guess I can see some gotchas in doing this that are not really an issue with the current setup. But you are welcome to convince me if you think this is actually the right way to go.

**Comment by mkoeppe** [comment]
One would just set `Cython < 3` so that it does not break when the elusive major new version finally drops. Other than that, there's likely no need to set additional version constraints.
Yes, build isolation builds CyLP kind-of in a virtual environment in which the version as declared in pyproject.toml is provisioned.

**Comment by tkralphs** [comment]
Sure, I'm willing to give this a go. I have to admit that my knowledge of Python keeps getting outdated and I'm not up on the latest ways of building/deploying packages. Last time I did a release of CyLP, I was still using `python setup.py build` to build and `python setup.py sdist` to generate the source distribution. Looking at the suggested Github Action made me realize that this whole workflow is deprecated now. At the moment, CyLP doesn't actually build correctly with `python -m build` because `numpy` is required. It would be nice to get CyLP set up like a modern package with `pyproject.toml`, etc.

**Comment by mkoeppe** [comment]
Here's a primer on pyproject.toml - https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by mkoeppe** [comment]
I'll send a PR.

**Comment by mkoeppe** [comment]
Time for a new release?
